public enum Placement {
    ONE_ON_ONE,
    TOP_WALL,
    RIGHT_WALL,
    LEFT_WALL,
    BOTTOM_WALL,
    TOP_RIGHT,
    TOP_LEFT,
    BOTTOM_RIGHT,
    BOTTOM_LEFT,
    BOTTOM_ONE_COL,
    TOP_ONE_COL,
    INTERNAL_ONE_COL,
    RIGHT_ONE_ROW,
    LEFT_ONE_ROW,
    INTERNAL_ONE_ROW,
    INTERNAL
}
